CC = gcc
CFLAGS = -O2 -flto -Ialogg/include -I/usr/local/include -DEOF_BUILD -DALLEGRO_LEGACY_STATICLINK
CXXFLAGS = $(CFLAGS)
LIBS = -lalleg -lallegro-static -lallegro_audio-static -lallegro_dialog-static --static -lallegro_main-static -logg -lvorbis -lvorbisfile -logg -lm -lfftw3 -lrubberband -lstdc++ -ldsound -lopengl32 -lglu32 -ldinput -ldxguid -lole32 -lwinmm -luuid -lkernel32 -lwinmm -lpsapi -luser32 -lcomdlg32 -lgdi32 -lshell32 -lole32 -ladvapi32 -lshlwapi
